spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/moonju?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate   # 개발용. 운영은 validate/none 권장
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    open-in-view: false

server:
  port: 4000

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-very-long-secret}
    expiry-minutes: 60